//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mon_pass_sql_express
{
    using System;
    using System.Collections.Generic;
    
    public partial class main
    {
        public long id { get; set; }
        public string pass_n { get; set; }
        public string exporter { get; set; }
        public string destination { get; set; }
        public string prod_name { get; set; }
        public string machine_n { get; set; }
        public string @base { get; set; }
        public string inoice { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public Nullable<decimal> qty { get; set; }
    }
}
