//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mon_pass_sql_express
{
    using System;
    using System.Collections.Generic;
    
    public partial class one_pass
    {
        public long id { get; set; }
        public string pass_n { get; set; }
        public string fi_name { get; set; }
        public string la_name { get; set; }
        public string pass_n_and_type { get; set; }
        public string personal_id { get; set; }
        public string destination { get; set; }
        public Nullable<System.DateTime> ttime { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
    }
}
